### ISSUE TITLE
Documentation for the callback request

### ISSUE THREAD

**Issue by samip5** [oasdiff/sync#5]
It would be great if the request that gets sent to the tenant's callback was documented.

**Comment by effoeffi** [comment]
It is covered in the 'How it works' section, but I've improved the documentation and the OAS. Please take a look at this [PR](https://github.com/oasdiff/sync/pull/6/files)

**Comment by samip5** [comment]
I couldn't find the payload that seemingly gets sent to the tenant's callback URL from the "how it works" section (seperate from slack URL), thus creating the issue.

Relevant part is this: <https://github.com/oasdiff/sync/blob/de6c890cea4ea3e1af7b799ab4545dea73fa6db6/openapi.yaml#L111-L115> which is not used at all?

**Comment by effoeffi** [comment]
Right, it is currently not in use. In the future, we may want to implement a map of callback types (like Slack) and callback URLs.
